name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            pixi-command: |
              pixi run -e linux test_linux a1 b2 c3
              echo "test input data" | pixi run -e linux ./arena_linux --test-input
              pixi run -e linux test_wordfreq_linux
              # TODO: `test_game_linux` doesn't work yet:
              pixi run -e linux build_game_linux
          - platform: macos
            os: macos-latest
            pixi-command: |
              pixi run -e macos test_macos a1 b2 c3
              echo "test input data" | pixi run -e macos ./arena_macos --test-input
              pixi run -e macos test_wordfreq_macos
              pixi run -e macos test_game_macos
          - platform: windows
            os: windows-latest
            pixi-command: |
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || exit /b 1
              pixi run -e windows test_windows a1 b2 c3 || exit /b 1
              echo test input data | pixi run -e windows arena_windows.exe --test-input || exit /b 1
              pixi run -e windows test_wordfreq_windows || exit /b 1
              pixi run -e windows test_game_windows || exit /b 1
          - platform: wasm
            os: ubuntu-latest
            pixi-command: |
              pixi run -e wasm test_wasm a1 b2 c3
              pixi run -e wasm test_base_wasm a1 b2 c3
              echo "test input data" | wasmtime --dir . arena.wasm --test-input
              echo "test input data" | wasmtime --dir . arena_base.wasm --test-input
              pixi run -e wasm test_wordfreq_wasm
              pixi run -e wasm build_game_wasm

    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.49.0
          cache: true

      - name: Setup wasmtime
        if: matrix.platform == 'wasm'
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "32.0.0"

      - name: Build and test ${{ matrix.platform }}
        if: matrix.platform != 'windows'
        run: ${{ matrix.pixi-command }}

      - name: Build and test ${{ matrix.platform }}
        if: matrix.platform == 'windows'
        run: ${{ matrix.pixi-command }}
        shell: cmd
