name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            pixi-command: pixi run -e linux test_linux
          - platform: macos
            os: macos-latest
            pixi-command: pixi run -e macos test_macos
          - platform: windows
            os: windows-latest
            pixi-command: |
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              REM pixi run -e windows test_windows
          - platform: wasm
            os: ubuntu-latest
            pixi-command: |
              pixi run -e wasm build_wasm
              wasmtime arena.wasm
    
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.49.0
          cache: true

      - name: Setup wasmtime
        if: matrix.platform == 'wasm'
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "32.0.0"

      - name: Build and test ${{ matrix.platform }}
        if: matrix.platform != 'windows'
        run: ${{ matrix.pixi-command }}

      - name: Build and test ${{ matrix.platform }}
        if: matrix.platform == 'windows'
        run: ${{ matrix.pixi-command }}
        shell: cmd